import { Lesson } from "@prisma/client";
import { Step } from "./steps"

/**
 * @swagger
 * components:
 *  schemas:
 *    LessonDTO:
 *      type: object
 *      properties:
 *        title:
 *          type: string
 *          description: The title of the lesson.
 *        start:
 *          type: string
 *          description: The day-time when the lesson starts. To set the actual date, leave it blank.
 *        end:
 *          type: string
 *          description: The day-time when the lesson finishes. If there's no end date, leave it blank.
 *        courseId:
 *          type: string
 *          description: The id of the existing course that uses this lesson.
 *        languageId:
 *          type: string
 *          description: The programming langages that will be used in the lesson.
 *      required:
 *        - title
 *        - courseId
 *        - languageId
 *      examples:
 *        id: 63158ff83cd164cc4fda4282
 *        description: Prints
 *        start: 09-09-00
 *        lessonId: 6314112d7ceeeb5338fdd955
 */
export interface LessonDTO extends Omit<Lesson, 'id'>{};

/**
 * @swagger
 * components:
 *  schemas:
 *    Lesson:
 *      allOf:
 *        - properties:
 *           id:
 *             type: string
 *             description: The autogenerated id of the lesson.
 *        - $ref: '#/components/schemas/LessonDTO'
 *        - type: object
 *      required:
 *          - start
 *          - id
 *      examples:
 *          id: 63158ff83cd164cc4fda4282
 *          description: Prints
 *          start: 09-09-00
 *          lessonId: 6314112d7ceeeb5338fdd955
 */
export { Lesson };

/**
 * @swagger
 * components:
 *  schemas:
 *    LessonNested:
 *      allOf:
 *        - $ref: '#/components/schemas/Lesson'
 *        - type: object
 *        - properties:
 *           steps:
 *             type: array
 *             items:
 *               $ref: '#/components/schemas/Step'
 *      required:
 *          - steps
 *      examples:
 *          id: 63158ff83cd164cc4fda4282
 *          description: Prints
 *          start: 09-09-00
 *          lessonId: 6314112d7ceeeb5338fdd955
 *          steps:
 *            - id: 63158ff83cd164cc4fda4281
 *              description: Print \"Hello world!\"
 *              lessonId: 63158ff83cd164cc4fda4282
 */
export interface LessonNested extends Lesson{
    steps: Step[]
}