import { Step } from "@prisma/client"
import { Template } from "./templates"
import { Solution } from "./solutions"

/**
 * @swagger
 * components:
 *  schemas:
 *    StepDTO:
 *      type: object
 *      properties:
 *        description:
 *          type: string
 *          description: The instructions of the step.
 *        lessonId:
 *          type: string
 *          description: The id of the existing lesson that uses this step.
 *      required:
 *        - description
 *        - lessonId
 *      examples:
 *        description: Print \"Hello world!\"
 *        lessonId: 6314112d7ceeeb5338fdd955
 */
export interface StepDTO extends Omit<Step, 'id'>{};

/**
 * @swagger
 * components:
 *  schemas:
 *    Step:
 *      allOf:
 *        - properties:
 *           id:
 *             type: string
 *             description: The autogenerated id of the step.
 *        - $ref: '#/components/schemas/StepDTO'
 *        - type: object
 *      required:
 *          - id
 *      examples:
 *        id: 63158ff83cd164cc4fda4282
 *        description: Print \"Hello world!\"
 *        lessonId: 6314112d7ceeeb5338fdd955
 */
export { Step };

/**
 * @swagger
 * components:
 *  schemas:
 *    StepNested:
 *      allOf:
 *        - $ref: '#/components/schemas/Step'
 *        - type: object
 *        - properties:
 *           template:
 *             $ref: '#/components/schemas/Template'
 *           solution:
 *             $ref: '#/components/schemas/Solution'
 *      examples:
 *        id: 63158ff83cd164cc4fda4282
 *        description: Print \"Hello world!\"
 *        lessonId: 6314112d7ceeeb5338fdd955
 *        template:
 *          id: 63158ff83cd164cc4fda4281
 *          name: main.py
 *          content: print(\"Hello!\")
 *          updateAt: 2022-09-04T07:18:20.250Z
 *          stepId: 63158ff83cd164cc4fda4282
 *        solution:
 *          id: 63158ff83cd164cc4fda4281
 *          name: main.py
 *          content: print(\"Hello world!\")
 *          updateAt: 2022-09-04T07:18:20.250Z
 *          stepId: 63158ff83cd164cc4fda4282
 */
export interface StepNested extends Step {
    template: Template | null;
    solution: Solution | null;
}